#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[user]
name            = "musaubrian"
email           = "musaubrian15@gmail.com"

[ui]
default-command = "log"
diff-editor = ":builtin"

[signing]
behavior        = "own"
backend         = "gpg"

[aliases]
difft           = ["diff", "--tool=difft"]
